FROM nginx:latest


RUN apt-get update && \
    apt-get -y install python3 python3-pip python3-dev python3-pil && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install crossplane



#RUN rm /etc/nginx/conf.d/default.conf
COPY wallak.conf /etc/nginx/conf.d
COPY wallak.conf /etc/nginx/sites-available/
#RUN /home/wkd/scrpt.py
RUN mkdir /etc/nginx/certs
COPY  nginx-selfsigned.crt /etc/nginx/certs
COPY nginx-selfsigned.key /etc/nginx/certs
COPY .htpasswd /etc/apache2/
#COPY wallak.conf /etc/nginx/sites-available
#4CMD ln -s 
#RUN apt-get update && apt-get install -y iputils-ping

#CMD service nginx restart

ARG port_arg
ARG host_arg
ARG cont_arg
COPY ./scrpt.py /etc/nginx/sites-available/
RUN python3 /etc/nginx/sites-available/scrpt.py $cont_arg $host_arg $port_arg


CMD ["nginx", "-g", "daemon off;"]
